In [1]:
import numpy as np

np.random.seed(101)

arr = np.random.randint(0,100,10)

arr

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [2]:
arr = np.random.randint(0,100,10)
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [3]:
arr.max()

93

In [4]:
arr.min()

4

In [5]:
arr.argmax()

8

In [9]:
arr.reshape((5,2))

array([[ 4, 63],
       [40, 60],
       [92, 64],
       [ 5, 12],
       [93, 40]])

In [11]:
array = np.arange(0,100).reshape((10,10))
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
array[:3,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [25]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

pic = Image.open("portrait.png")
type(pic)

pic_arr = np.asarray(pic)

In [41]:
pic_arr = pic_arr.copy()
plt.imshow(pic_arr[:,:,1], cmap='gray')
pic_arr[:,:,2] = 0
plt.imshow(pic_arr)